# Generated by Django 2.2.2 on 2019-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
