# Generated by Django 2.2.2 on 2019-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgll_app', '0002_auto_20190619_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
