# Generated by Django 2.2.2 on 2019-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgll_app', '0006_posts_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='summary',
            field=models.CharField(default='Khatagaha Graphite Lanaka Limited updates', max_length=200),
        ),
    ]
