# Generated by Django 2.2.2 on 2019-08-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgll_app', '0007_auto_20190624_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_name', models.CharField(max_length=70)),
                ('carbon_grade_1', models.CharField(max_length=10)),
                ('grade_1_availability', models.CharField(default='Available', max_length=15)),
                ('carbon_grade_2', models.CharField(blank=True, max_length=10)),
                ('grade_2_availability', models.CharField(blank=True, max_length=15)),
                ('carbon_grade_3', models.CharField(blank=True, max_length=10)),
                ('grade_3_availability', models.CharField(blank=True, max_length=15)),
                ('carbon_grade_4', models.CharField(blank=True, max_length=10)),
                ('grade_4_availability', models.CharField(blank=True, max_length=15)),
                ('particle_size', models.CharField(blank=True, max_length=10)),
                ('product_summary', models.CharField(default='Product of Kahatagha Graphite Lanka Limited', max_length=200)),
            ],
        ),
    ]
